[[constraint]]
  branch = "master"
  name = "emersyx.net/emersyx_apis"

[[constraint]]
  branch = "master"
  name = "emersyx.net/emersyx_log"

[[constraint]]
  name = "github.com/BurntSushi/toml"
  version = "0.3.0"
